language: node_js
node_js:
- '11'
cache:
  directories:
  - node_modules
deploy:
  skip_cleanup: true
  provider: npm
  email: quentin@frontapp.com
  api_key:
    secure: D7MoJCnUUMxMAZnMP2ageDITqDmd36AsAWpUpH8gPJzzUu9hAp0GLNI6veWn5o6PoEGRAsZC/AcXA2XVex1sgWkV0QatfkNPapTkT4k5RrKD2yeA+MRc/nxy/pi7V5ai42gVbzE6r7m456TnIi2boRzWV0jY4S4ReN/Uvqq2voXbtHNlkAqlr2B30dezZZWS2sq/vty9K6XqX0ATrO60vzOXo7vtMzE61pf7BnuSof5UW8XjUQY1+kWokETHhuFvss9jgYgHB4Q2TtSBOMKWw7JpBgR3lyf1/4WZwSSCcWOOGfLqaPjae7nk8/ozysK6wkJT6x9StDzIaqpPicNhDeAuMgKB51JJvu++vINTVfhNCjvT0oAkxC2jbh8YJSqw1kwghkw1/X0j+T94yGZFxQHiOToq7tCch7ic7p0Un+U94DVm+C2V7Ppa/tDLfQaOgFYxDkRqjoGt/2xQyjj4iB7awudtRT78GAvNo9ZufRozCI+SKZycr+nt2YumsHrMWkaLcghp2bBch4HxOvRsycfW3wc4VsmpXvF90//pVAVCzEq1YmIiR8aLCJ5NHmpQL+8schszWYDLc+M/0zhInA9BP2LzK4Aq28ncrwL6OGirBoa6YeCOxtGbb/DUWLObu2USOpiAj8uzzY9pImX1YUcba3vzKoylBXpY54EjFjo=
  on:
    repo: quentez/talonjs
    tags: true
    branch: master
